### PR TITLE
add draft for bio.tools crosswalk

### PR DESCRIPTION
**Pull request by hmenager**
based on the mapping from @albangaignard and @joncison

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks! Can you also drop in a link in this thread with a bit more background about bio.tools?

**Comment by hmenager** [comment]
Sure. bio.tools is the ELIXIR registry for "essential scientific and technical information about software tools, databases and services for bioinformatics and the life sciences". It is available at https://bio.tools. Please tell me if you need other information.

**Comment by cboettig** [comment]
That's perfect, thanks!  

Ideally we'd also have a page over on https://github.com/codemeta/codemeta.github.io/tree/hugo/content/crosswalk, which will add this one to the website listing and also provide a little more context about what `bio.tools` is all about (and perhaps more importantly, where users can expect to come across software marked up in this vocabulary).  I do wish we had a more low-friction way for contributors to add this material, but perhaps creating an .Rmd similar to the ones there for some of the other terms would be feasible?

**Comment by hmenager** [comment]
Hi @cboettig I can provide this page, I'll try to take care of it at the latest by the end of next week.

**Comment by hmenager** [comment]
Hello again, I tried to come up with a PR following your instructions. Feel free to correct, I used the Rmd, but I do not speak R.
PR is there: https://github.com/codemeta/codemeta.github.io/pull/21

**Pull request merged**
