### PR TITLE
Add reference publication equivalent

### PR DESCRIPTION
**Pull request by physikerwelt**
describedBySource seems to be a reasonable equivalent to referencePublication

### CODE REVIEW

**Comment by dgarijo** [comment]
+1. Supporting example: https://www.wikidata.org/wiki/Q118564029

**Comment by physikerwelt** [comment]
@moranegg, do you know, by chance, who could review this PR? It has been a while.

**Comment by dgarijo** [comment]
I guess mine could be considered a review?

**Comment by moranegg** [comment]
Hi @physikerwelt for the ping.
We have a big delay with the maintenance of CodeMeta because of lack of time and a more standardized community governance which doesn't make things faster :) 

Thanks @dgarijo for the review.
For me it's a go to merge, but I'm answering this on my phone.. 
Will get back to you ASAP.

**Review by progval — APPROVED** [review]

**Pull request merged**
