### PR TITLE
Add the Software Entities Model

### PR DESCRIPTION
**Pull request by zoidy**
From here:
http://rrr.cs.st-andrews.ac.uk/wp-content/uploads/2015/10/guidelines-software-identification.pdf

This is a DataCite-based schema to represent software. It's slightly different than the existing column for Datacite which is why I added it.

Note that this is a partial map as some of the concepts don't appear to be present in CodeMeta.

### CODE REVIEW

**Comment by cboettig** [comment]
@zoidy Haven't had a chance to take a close look, but this looks great. What version of the DataCite schema is this based on?  (@mfenner has mentioned an upcoming version 4.0 they have been working on, and might have comments on this PR as well)

**Comment by mfenner** [comment]
Not really any changes in the upcoming DataCite Schema 4.0 that would be relevant here. The Schema will be released in Q1 2016.

**Comment by zoidy** [comment]
@cboettig @mfenner The document doesn't state specifically but it's probably 3.1. At IDCC last month, the authors [made reference](http://www.dcc.ac.uk/webfm_send/2169) to the use of the potential use of descriptionType="TechnicalInfo" for the Description field. If I'm not mistaken, TechnicalInfo is only present in 4.0

**Comment by mbjones** [comment]
This looks good, @zoidy -- but it would also be useful to have the concepts that are not covered by codemeta represented as new Concepts in the table.  How many new concepts are there?  I briefly read the JISC report and it seems like there is a lot of overlap, albeit some nice conceptualizations around the model for software.  I merged this as is, but maybe you could do another PR with the additional concepts?

**Pull request merged**
