### PR TITLE
Update crosswalks to allow the aggregation of every properties

### PR DESCRIPTION
**Pull request by bact**
- Update crosswalk CSV files to have equal number of properties, so the `scripts/aggregate.py` can properly generate every properties (73 properties) (currently it will produce only 70, omitting the last three properties)
  - Add [ readme, hasSourceCode, isSourceCodeOf ] properties to `Citation File Format 1.2.0.csv`
  - Remove all lines with only one comma at the end of CSVs

- Update `SciCrunchRegistry.csv`
  - Line 21-74: Remove Unicode Character 'NO-BREAK SPACE' (U+00A0)

- Update `ISO_19115-1.csv`
  - Line 1: Add missing 2nd column header name
  - Line 23-24: Remove a leading space from the 2nd field
  - Line 37: Use ' instead of `, around pointOfContact, to be consistent with other rows

### CODE REVIEW

**Comment by bact** [comment]
Btw, I have made no changes to newline characters (\r\n \n) but Git reports changes in `Cargo.csv`, `Citation File Format 1.2.0.csv`, and `Julia Project.csv` at Line 4 and 58-62 (same line numbers for all 3 files) and Line 72-73 (only for Julia). Does it possible that Git is trying to normalize newlines of those lines to make them consistent with the rest of the same files?

**Comment by progval** [comment]
> Btw, I have made no changes to newline characters (\r\n \n) but Git reports changes in `Cargo.csv`, `Citation File Format 1.2.0.csv`, and `Julia Project.csv` at Line 4 and 58-62 (same line numbers for all 3 files) and Line 72-73 (only for Julia).
> 
> Does it possible that Git is trying to normalize newlines of those lines to make them consistent with the rest of the same files?

It's because these particular lines had `\r\n` ends while other lines in the files have `\n` ends and your editor fixed them to all be `\n` (as they should).

**Review by progval — APPROVED** [review]

**Comment by bact** [comment]
@progval  So there anything I should amend further for this PR?
Thank you.

**Comment by progval** [comment]
Sorry, I forgot about it. Merged, thanks!

**Comment by bact** [comment]
No worries. Thank you as well.

**Pull request merged**
