### PR TITLE
change embargoDate to embargoEndDate

### PR DESCRIPTION
**Pull request by tmorrell**
Per discussion in https://github.com/codemeta/codemeta/issues/254

### CODE REVIEW

**Comment by cboettig** [comment]
:+1: LGTM.  @mbjones ?

**Comment by moranegg** [comment]
Add label #v3.0

This PR is candidate for a discussion, it changes the spec, we should also label it #discussion.
Discussion will be open until March 15th and we will then proceed to a vote from March 15th to March 25th.

**Comment by moranegg** [comment]
We will keep `embargoDate` and add `embargoEndDate` to the v3.0 with a mention of deprecated for the former on the property description. This is to keep the v3.0 compatible with v2.0.
We will delete the `embargoDate` property on v4.0.

**Comment by progval** [comment]
@tmorrell Could you rebase your PR to resolve merge conflicts? thanks!

**Comment by moranegg** [comment]
@progval if you have the time, could you rebase and resolve the issue to move forward to a V3.0 release.
Thanks for the help!

**Comment by progval** [comment]
Replaced by #314 (which fixes merge conflicts)

**Pull request closed without merging**
